- name: expose mysql to public
  lineinfile:
    path: "{{ conf }}"
    regexp: '^bind-address'
    line: '#bind-address           = 127.0.0.1'

- name: configure database master server
  lineinfile: 
    path: "{{ conf }}"
    line: "{{ item }}"
  with_items:
    - "server-id               = 1"
    - "log_bin                 = {{ logbin }}"
    - "innodb_flush_log_at_trx_commit = 1"
    - "sync_binlog             = 1"
  when: inventory_hostname == 'master'

- name: create database user replication
  mysql_user:
    login_user: "{{ master_user }}"
    login_password: "{{ master_pass }}"
    host: "{{ ipslave }}"
    name: "{{ user }}"
    password: "{{ pass }}"
    priv: "*.*:REPLICATION SLAVE"
    state: present
  when: inventory_hostname == 'master'

- name: configure database master server 
  lineinfile: 
    path: "{{ conf }}"
    line: "{{ item }}"
  with_items:
    - "server-id                = 2"
    - "relay-log-index		= slave-relay-bin.index"
    - "relay-log		= slave-relay-bin"
  when: inventory_hostname == 'slave'

- name: restart service mysql
  systemd:
    name: mysql
    state: restarted

- name: configure replication on slave
  mysql_replication:
    mode: changemaster
    master_host: "{{ ipmaster }}"
    master_log_file: ''
    master_log_pos: "{{ master_log_pos }}"
    master_user: "{{ user }}"
    master_password: "{{ pass }}"
    login_user: "{{ slave_user }}"
    login_password: "{{ slave_pass }}"
  when: inventory_hostname == 'slave'

- name: start replication
  mysql_replication:
    mode: startslave
    login_user: "{{ slave_user }}"
    login_password: "{{ slave_pass }}"
  when: inventory_hostname == 'slave'

