- name: expose mysql to public
  lineinfile:
    path: "{{ conf }}"
    regexp: '^bind-address'
    line: '#bind-address           = 127.0.0.1'

- include: master.yml
  tags: [mysql, master-config]

- include: slave.yml
  tags: [mysql, slave-config]

