- name: configure database master server
  lineinfile: 
    path: "{{ conf }}"
    line: "{{ item }}"
  with_items:
    - "server-id               = 1"
    - "log_bin                 = {{ logbin }}"
    - "innodb_flush_log_at_trx_commit = 1"
    - "sync_binlog             = 1"
  when: inventory_hostname == 'master'

- name: create database user replication
  mysql_user:
    login_user: "{{ master_user }}"
    login_password: "{{ master_pass }}"
    host: "{{ ipslave }}"
    name: "{{ user }}"
    password: "{{ pass }}"
    priv: "*.*:REPLICATION SLAVE"
    state: present
  when: inventory_hostname == 'master'

- name: restart service mysql
  systemd:
    name: mysql
    state: restarted
