- name: configure database slave server 
  lineinfile: 
    path: "{{ conf }}"
    line: "{{ item }}"
  with_items:
    - "server-id                = 2"
    - "relay-log-index		= slave-relay-bin.index"
    - "relay-log		= slave-relay-bin"
  when: inventory_hostname == 'slave'

- name: restart service mysql
  systemd:
    name: mysql
    state: restarted

- name: configure replication on slave
  mysql_replication:
    mode: changemaster
    master_host: "{{ ipmaster }}"
    master_log_file: ''
    master_log_pos: "{{ master_log_pos }}"
    master_user: "{{ user }}"
    master_password: "{{ pass }}"
    login_user: "{{ slave_user }}"
    login_password: "{{ slave_pass }}"
  when: inventory_hostname == 'slave'

- name: start replication
  mysql_replication:
    mode: startslave
    login_user: "{{ slave_user }}"
    login_password: "{{ slave_pass }}"
  when: inventory_hostname == 'slave'

